export const LOAD_POSTS_START = "LOAD_POSTS_START"
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR"

export const VIEW_POSTS_START = "VIEW_POSTS_START"
export const VIEW_POSTS_SUCCESS = "VIEW_POSTS_SUCCESS"
export const VIEW_POSTS_ERROR = "VIEW_POSTS_ERROR"


